-- ============================================================================
-- Export Document Management System — Postgres schema (Supabase)
-- ----------------------------------------------------------------------------
-- SQLite (sql.js / IndexedDB) からの移植版。
--
-- 設計メモ:
--   * id は "generated BY DEFAULT as identity" — 移行時に既存IDを明示INSERTできる
--   * 業務日付 (etd, invoice_date 等) は SQLite と同じ TEXT のまま
--     （first_reg_date='AUGUST / 2024' のような非ISO値が混在するため。
--       型の厳格化は Step 2 のリファクタで検討）
--   * created_at 等のシステム時刻は timestamptz
--   * users テーブルは移植しない — Supabase Auth (auth.users) + profiles に置換
--
-- 実行方法: Supabase Dashboard → SQL Editor → このファイルを貼り付けて Run
-- ============================================================================

-- ---------------------------------------------------------------------------
-- profiles — auth.users と1:1。アプリ内ロールと取引先(party)の紐付けを保持
-- ---------------------------------------------------------------------------
create table if not exists public.profiles (
  id            uuid primary key references auth.users(id) on delete cascade,
  username      text unique,
  display_name  text,
  -- 'admin' | 'editor' | 'viewer' — 社内スタッフ
  -- 'buyer' | 'ap_holder'         — 外部ポータルユーザー (party_id 必須)
  role          text not null default 'viewer',
  party_id      bigint,            -- buyer/ap_holder の場合に parties.id を指す
  is_active     boolean not null default true,
  created_at    timestamptz not null default now()
);

-- auth.users 作成時に profiles 行を自動作成（デフォルトは最小権限 viewer）
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, display_name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'display_name', new.email))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- parties — Seller / Buyer / Notify / AP Holder
-- ---------------------------------------------------------------------------
create table if not exists public.parties (
  id                bigint generated by default as identity primary key,
  role              text not null,           -- seller | buyer | notify | ap_holder
  company_name      text not null,
  address           text,
  tel               text,
  email             text,
  attn_name         text,
  attn_tel          text,
  bank_name         text,
  bank_branch       text,
  bank_address      text,
  bank_branch_code  text,
  bank_account_no   text,
  bank_account_name text,
  bank_swift        text,
  created_at        timestamptz not null default now()
);

-- profiles.party_id の FK（parties 作成後に張る）
alter table public.profiles
  drop constraint if exists profiles_party_id_fkey;
alter table public.profiles
  add constraint profiles_party_id_fkey
  foreign key (party_id) references public.parties(id) on delete set null;

-- ---------------------------------------------------------------------------
-- vehicle_models — 車両モデルマスター
-- ---------------------------------------------------------------------------
create table if not exists public.vehicle_models (
  id               bigint generated by default as identity primary key,
  category         text default 'car',       -- car | bike
  maker            text,
  model_name       text,
  model_code       text,
  engine_capacity  text,
  displacement_cc  text,
  fuel             text,
  weight_kg        text,
  measurement_m3   text,
  hs_code          text,
  specification    text,
  note             text,
  created_at       timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- cases — 案件（中核テーブル）
-- ---------------------------------------------------------------------------
create table if not exists public.cases (
  id                 bigint generated by default as identity primary key,
  case_code          text,
  invoice_ref_no     text,
  invoice_date       text,
  payment_due_date   text,
  seller_id          bigint references public.parties(id),
  primary_buyer_id   bigint references public.parties(id),
  vehicle_model_id   bigint references public.vehicle_models(id),
  qty                integer default 1,
  amount_jpy         bigint,

  -- 車両情報
  description        text,
  maker              text,
  model_name         text,
  year_month         text,
  model_code         text,
  chassis_no         text,
  engine_no          text,
  engine_capacity    text,
  displacement_cc    text,
  mileage            text,
  exterior_color     text,
  fuel               text,
  auction_grade      text,
  weight_kg          text,
  measurement_m3     text,
  hs_code            text,
  specification      text,
  remark             text,

  -- 船積条件
  vessel_name        text,
  voyage_no          text,
  etd                text,
  eta                text,
  port_of_loading    text,
  port_of_discharge  text,
  place_of_delivery  text,
  type_of_service    text,
  delivery_term      text,

  -- Shipping Instruction
  shipping_company           text,
  booking_no                 text,
  volume                     text,
  freight_term               text,
  place_of_receipt           text,
  place_of_issue             text,
  no_of_original_bl          text,
  local_vessel               text,
  local_voyage_no            text,
  cut_date                   text,
  booked_by                  text,
  forwarder                  text,
  notify_party_id            bigint references public.parties(id),
  warehouse_name             text,
  warehouse_date             text,
  shipping_instruction_note  text,

  -- Export Certificate / Preserved Record
  registration_no            text,
  registration_date          text,
  first_reg_date             text,
  previous_reg_no            text,
  reference_no               text,
  export_cert_no             text,
  preserve_record_no         text,
  export_scheduled_date      text,
  vehicle_use                text,
  vehicle_purpose            text,
  body_type                  text,
  classification_vehicle     text,
  classification_body_no     text,
  fixed_number               text,
  max_carry_weight           text,
  gross_weight               text,
  length_cm                  text,
  width_cm                   text,
  height_cm                  text,
  ff_weight                  text,
  fr_weight                  text,
  rf_weight                  text,
  rr_weight                  text,
  spec_no                    text,
  classification_no          text,
  owner_code                 text,
  fuel_classification_spec   text,
  engine_model               text,
  maker_code                 text,
  issuer_title               text,

  -- ステータス
  progress_status            text default 'inquiry',
  payment_status             text default 'unpaid',
  status_note                text,
  status_updated_at          timestamptz,

  -- タグ / お気に入り / カテゴリ
  tags                       text,
  is_favorite                boolean default false,
  vehicle_category           text default 'car',

  -- AP Holder（案件レベルのデフォルト）
  ap_holder_id               bigint references public.parties(id),

  -- 輸出抹消手続き
  dereg_transfer_needed      boolean default false,

  created_at                 timestamptz not null default now()
);

create index if not exists idx_cases_primary_buyer on public.cases(primary_buyer_id);
create index if not exists idx_cases_ap_holder     on public.cases(ap_holder_id);
create index if not exists idx_cases_category      on public.cases(vehicle_category);
create index if not exists idx_cases_progress      on public.cases(progress_status);

-- ---------------------------------------------------------------------------
-- case_documents — 書類ごとの Buyer / AP Holder / 条件
-- ---------------------------------------------------------------------------
create table if not exists public.case_documents (
  id                bigint generated by default as identity primary key,
  case_id           bigint not null references public.cases(id) on delete cascade,
  doc_type          text not null,
  buyer_id          bigint references public.parties(id),
  ap_holder_id      bigint references public.parties(id),
  doc_date          text,
  doc_ref_no        text,
  payment_due_date  text,
  terms_condition   text,
  atten_text        text,
  custom_fields     text,
  unique (case_id, doc_type)
);

create index if not exists idx_case_documents_case on public.case_documents(case_id);

-- ---------------------------------------------------------------------------
-- registration_events — Preserved Record 用の登録履歴
-- ---------------------------------------------------------------------------
create table if not exists public.registration_events (
  id                      bigint generated by default as identity primary key,
  case_id                 bigint not null references public.cases(id) on delete cascade,
  sort_order              integer default 0,
  event_date              text,
  event_type              text,
  acceptance_number       text,
  registration_number     text,
  owner_name              text,
  owner_address           text,
  user_name               text,
  user_address            text,
  principal_place_of_use  text,
  scheduled_export_date   text,
  notes                   text
);

create index if not exists idx_reg_events_case on public.registration_events(case_id);

-- ---------------------------------------------------------------------------
-- payments — 入金明細
-- ---------------------------------------------------------------------------
create table if not exists public.payments (
  id            bigint generated by default as identity primary key,
  case_id       bigint not null references public.cases(id) on delete cascade,
  payment_date  text,
  amount_jpy    bigint,
  method        text,
  reference_no  text,
  note          text,
  created_at    timestamptz not null default now()
);

create index if not exists idx_payments_case on public.payments(case_id);

-- ---------------------------------------------------------------------------
-- costs — 原価明細
-- ---------------------------------------------------------------------------
create table if not exists public.costs (
  id          bigint generated by default as identity primary key,
  case_id     bigint not null references public.cases(id) on delete cascade,
  cost_type   text,
  amount_jpy  bigint,
  vendor      text,
  cost_date   text,
  note        text,
  created_at  timestamptz not null default now()
);

create index if not exists idx_costs_case on public.costs(case_id);

-- ---------------------------------------------------------------------------
-- photos — 車両写真
--   Step 1: data_url(Base64) のまま移行（ロスレス）
--   Step 2: Supabase Storage に移し、storage_path に切替予定
-- ---------------------------------------------------------------------------
create table if not exists public.photos (
  id            bigint generated by default as identity primary key,
  case_id       bigint not null references public.cases(id) on delete cascade,
  filename      text,
  mime_type     text,
  data_url      text,
  storage_path  text,           -- Step 2 で使用予定
  caption       text,
  sort_order    integer default 0,
  created_at    timestamptz not null default now()
);

create index if not exists idx_photos_case on public.photos(case_id);

-- ---------------------------------------------------------------------------
-- doc_issue_log — 書類発行履歴
-- ---------------------------------------------------------------------------
create table if not exists public.doc_issue_log (
  id         bigint generated by default as identity primary key,
  case_id    bigint not null references public.cases(id) on delete cascade,
  doc_type   text not null,
  issued_at  timestamptz not null default now(),
  version    integer default 1,
  issued_by  text,
  note       text
);

create index if not exists idx_doc_issue_case on public.doc_issue_log(case_id);

-- ---------------------------------------------------------------------------
-- audit_log — 監査ログ
--   actor_user_id: 旧ローカルDBの整数ID（移行データの保全用）
--   actor_uuid:    Supabase Auth ユーザー（Step 2 以降の新規ログで使用）
-- ---------------------------------------------------------------------------
create table if not exists public.audit_log (
  id              bigint generated by default as identity primary key,
  actor_user_id   bigint,
  actor_uuid      uuid references auth.users(id),
  actor_username  text,
  action          text,
  target_type     text,
  target_id       bigint,
  summary         text,
  ip              text,
  created_at      timestamptz not null default now()
);

create index if not exists idx_audit_created on public.audit_log(created_at desc);

-- ---------------------------------------------------------------------------
-- ap_holder_history — AP Holder 変更履歴
-- ---------------------------------------------------------------------------
create table if not exists public.ap_holder_history (
  id                bigint generated by default as identity primary key,
  case_id           bigint not null references public.cases(id) on delete cascade,
  old_ap_holder_id  bigint references public.parties(id),
  new_ap_holder_id  bigint references public.parties(id),
  changed_at        timestamptz not null default now(),
  changed_by        text,
  note              text
);

create index if not exists idx_ap_history_case on public.ap_holder_history(case_id, changed_at desc);

-- ---------------------------------------------------------------------------
-- case_dereg_checklist — 輸出抹消手続きチェックリスト
-- ---------------------------------------------------------------------------
create table if not exists public.case_dereg_checklist (
  id            bigint generated by default as identity primary key,
  case_id       bigint not null references public.cases(id) on delete cascade,
  item_key      text not null,
  completed     boolean default false,
  completed_at  timestamptz,
  note          text,
  unique (case_id, item_key)
);

create index if not exists idx_dereg_case on public.case_dereg_checklist(case_id);

-- ---------------------------------------------------------------------------
-- settings — システム設定 (key-value)
-- ---------------------------------------------------------------------------
create table if not exists public.settings (
  key    text primary key,
  value  text
);

-- ---------------------------------------------------------------------------
-- reset_all_sequences — 移行で明示IDをINSERTした後にシーケンスを進める RPC
-- （admin ロールのみ実行可。クライアントから supabase.rpc() で呼ぶ）
-- ---------------------------------------------------------------------------
create or replace function public.reset_all_sequences()
returns void
language plpgsql
security definer set search_path = public
as $$
declare
  r record;
begin
  -- admin チェック
  if not exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin' and is_active
  ) then
    raise exception 'admin role required';
  end if;

  for r in
    select
      t.relname as table_name,
      a.attname as column_name,
      pg_get_serial_sequence(quote_ident(t.relname), a.attname) as seq_name
    from pg_class t
    join pg_attribute a on a.attrelid = t.oid
    join pg_namespace n on n.oid = t.relnamespace
    where n.nspname = 'public'
      and a.attidentity in ('a', 'd')
      and t.relkind = 'r'
  loop
    if r.seq_name is not null then
      execute format(
        'select setval(%L, coalesce((select max(%I) from %I), 0) + 1, false)',
        r.seq_name, r.column_name, r.table_name
      );
    end if;
  end loop;
end;
$$;
