-- ============================================================================
-- 003: 提出書類アーカイブテーブル（001作成後に追加された機能の追従）
-- ----------------------------------------------------------------------------
-- 実行方法: SQL Editor で実行（001/002 実行済みの環境に追加適用）
-- ============================================================================

create table if not exists public.case_documents_archive (
  id           bigint generated by default as identity primary key,
  case_id      bigint not null references public.cases(id) on delete cascade,
  form_key     text not null,
  filename     text,
  mime_type    text,
  data_url     text,
  uploaded_at  timestamptz not null default now(),
  uploaded_by  text,
  note         text
);

create index if not exists idx_archive_case
  on public.case_documents_archive(case_id, form_key);

alter table public.case_documents_archive enable row level security;

-- スタッフ: 読み書き / ポータルユーザー: 自分の案件の閲覧のみ
drop policy if exists archive_select on public.case_documents_archive;
create policy archive_select on public.case_documents_archive for select
  using (public.is_staff() or public.party_can_access_case(case_id));

drop policy if exists archive_write on public.case_documents_archive;
create policy archive_write on public.case_documents_archive for all
  using (public.can_edit())
  with check (public.can_edit());
