-- ============================================================================
-- 004_shop.sql — 公開ショップ（マレーシア顧客向け購入サイト）
-- ----------------------------------------------------------------------------
-- - shop_listings:  掲載情報（どの案件を・いくらで・どんな英語説明で公開するか）
-- - shop_inquiries: 購入申込・問い合わせ（未ログインの一般客が送信）
-- - shop_catalog / shop_listing_photos: anon に公開する読み取り専用ビュー。
--   ビューは所有者権限で実行されるため、公開して安全なカラムだけを厳選する。
--   原価・Buyer・チェシ番号・船積詳細などの社内情報は絶対に含めないこと。
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. 掲載テーブル
-- ---------------------------------------------------------------------------
create table if not exists public.shop_listings (
  id             bigint generated by default as identity primary key,
  case_id        bigint not null references public.cases(id) on delete cascade,
  status         text not null default 'draft'
                 check (status in ('draft', 'published', 'reserved', 'sold')),
  title_en       text,            -- 例: "2024 TOYOTA ALPHARD Z"
  description_en text,            -- 英語の紹介文（specificationとは別の自由文）
  price_amount   numeric,         -- 表示価格
  price_currency text not null default 'USD'
                 check (price_currency in ('USD', 'JPY', 'MYR')),
  price_note_en  text,            -- 例: "CIF Port Klang" / "FOB Japan"
  published_at   timestamptz,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  unique (case_id)
);

create index if not exists idx_shop_listings_status on public.shop_listings(status);

alter table public.shop_listings enable row level security;

-- スタッフ（editor以上）が管理。閲覧はスタッフ全員可
drop policy if exists shop_listings_staff_select on public.shop_listings;
create policy shop_listings_staff_select on public.shop_listings
  for select to authenticated using (public.is_staff());

drop policy if exists shop_listings_staff_write on public.shop_listings;
create policy shop_listings_staff_write on public.shop_listings
  for all to authenticated using (public.can_edit()) with check (public.can_edit());

-- ---------------------------------------------------------------------------
-- 2. 購入申込・問い合わせテーブル
-- ---------------------------------------------------------------------------
create table if not exists public.shop_inquiries (
  id            bigint generated by default as identity primary key,
  listing_id    bigint references public.shop_listings(id) on delete set null,
  inquiry_type  text not null default 'purchase'
                check (inquiry_type in ('purchase', 'question')),
  customer_name text not null,
  email         text not null,
  phone         text,
  country       text default 'Malaysia',
  message       text,
  status        text not null default 'new'
                check (status in ('new', 'in_progress', 'converted', 'closed')),
  admin_note    text,
  party_id      bigint references public.parties(id),  -- Buyer変換後の紐付け
  created_at    timestamptz not null default now()
);

create index if not exists idx_shop_inquiries_status on public.shop_inquiries(status);

alter table public.shop_inquiries enable row level security;

-- 未ログイン客は INSERT のみ（自分の申込すら読み返せない = 情報漏えいゼロ）
drop policy if exists shop_inquiries_public_insert on public.shop_inquiries;
create policy shop_inquiries_public_insert on public.shop_inquiries
  for insert to anon with check (
    inquiry_type in ('purchase', 'question')
    and status = 'new'
    and party_id is null
    and admin_note is null
    and char_length(customer_name) between 1 and 200
    and char_length(email) between 5 and 320
    and (message is null or char_length(message) <= 4000)
  );

-- スタッフは閲覧・更新可
drop policy if exists shop_inquiries_staff_select on public.shop_inquiries;
create policy shop_inquiries_staff_select on public.shop_inquiries
  for select to authenticated using (public.is_staff());

drop policy if exists shop_inquiries_staff_update on public.shop_inquiries;
create policy shop_inquiries_staff_update on public.shop_inquiries
  for update to authenticated using (public.can_edit()) with check (public.can_edit());

drop policy if exists shop_inquiries_staff_delete on public.shop_inquiries;
create policy shop_inquiries_staff_delete on public.shop_inquiries
  for delete to authenticated using (public.is_admin());

-- ---------------------------------------------------------------------------
-- 3. 公開ビュー（anonが読む唯一の窓口。公開安全カラムのみ）
-- ---------------------------------------------------------------------------
-- ビューはowner権限で下のテーブルを読む（RLSバイパス）ため、
-- where句で published 系のみに絞り、カラムを厳選する。
create or replace view public.shop_catalog as
select
  l.id,
  l.status,
  l.title_en,
  l.description_en,
  l.price_amount,
  l.price_currency,
  l.price_note_en,
  l.published_at,
  c.vehicle_category,
  c.maker,
  c.model_name,
  c.model_code,
  c.year_month,
  c.mileage,
  c.exterior_color,
  c.fuel,
  c.engine_capacity,
  c.displacement_cc,
  c.auction_grade,
  c.specification,
  (
    select p.data_url from public.photos p
    where p.case_id = c.id
    order by p.sort_order nulls last, p.id
    limit 1
  ) as cover_photo
from public.shop_listings l
join public.cases c on c.id = l.case_id
where l.status in ('published', 'reserved', 'sold');

create or replace view public.shop_listing_photos as
select
  p.id,
  l.id as listing_id,
  p.data_url,
  p.caption,
  p.sort_order
from public.photos p
join public.shop_listings l on l.case_id = p.case_id
where l.status in ('published', 'reserved', 'sold');

grant select on public.shop_catalog to anon, authenticated;
grant select on public.shop_listing_photos to anon, authenticated;

-- shop_inquiries への anon insert に必要な最小権限（このテーブルのIDシーケンスのみ）
grant insert on public.shop_inquiries to anon;
grant usage on sequence public.shop_inquiries_id_seq to anon;
